#Requires -Version 7.4
#Requires -Modules @{ ModuleName = 'PnP.PowerShell'; ModuleVersion = '3.4.1' }

<#
.SYNOPSIS
    One-time bootstrap of an iSOC Blueprint SharePoint site for one
    Sentinel workspace. Run interactively by a SharePoint administrator.

.DESCRIPTION
    Everything inside the site is generated by Publish-SentinelDocsSite.ps1
    on every pipeline run. This script does the part a pipeline should not
    have the rights to do, once:

      1. Creates the communication site (blank design) if it does not
         exist yet.
      2. Checks the tenant app catalog exists (site collection app
         catalogs depend on it) and adds a site collection app catalog to
         this site, so the dashboard web part is deployed to this site
         only and the pipeline never needs tenant-wide app rights.
      3. Grants the publisher app registration FullControl on this site
         only (Sites.Selected). FullControl is the level the site
         collection app catalog, home page and navigation changes need.
      4. Turns off page comments and turns on the mega menu, which suits
         the generated family navigation.
      5. Optionally deploys the dashboard web part package, so the first
         pipeline run does not wait for it to appear.

    It is safe to re-run: each step checks before it changes anything.

    Prerequisites:
      - The publisher app registration has the SharePoint (not Microsoft
        Graph) application permission Sites.Selected, with admin consent,
        and a federated credential for each pipeline.
      - The app you sign in with (-ClientId) has delegated
        Sites.FullControl.All (to grant site access) and you are a
        SharePoint administrator.

    Site membership is the privacy boundary: the site shows tenant
    configuration, findings and role assignments. Keep the Visitors and
    Members groups to the people who should read it.

.PARAMETER SiteUrl
    URL of the site to create or prepare, for example
    https://contoso.sharepoint.com/sites/isoc-law-sentinel-prod.

.PARAMETER Title
    Site title used when creating the site. Defaults to 'iSOC Blueprint'.

.PARAMETER Owner
    UPN of the site owner, used when creating the site.

.PARAMETER PublisherAppId
    Client (application) id of the publisher app registration the
    pipelines use.

.PARAMETER PublisherAppName
    Display name recorded with the site permission grant.

.PARAMETER ClientId
    Your Entra app registration for interactive PnP sign-in.

.PARAMETER Tenant
    Tenant, for example contoso.onmicrosoft.com.

.PARAMETER TenantAdminUrl
    SharePoint admin centre URL. Defaults to https://<tenant>-admin.sharepoint.com
    derived from -SiteUrl.

.PARAMETER AppPackagePath
    Optional path to sentinel-navigator.sppkg to deploy now.

.EXAMPLE
    ./Tools/Documenter/SharePoint/Initialize-SentinelDocsSite.ps1 `
        -SiteUrl 'https://contoso.sharepoint.com/sites/isoc-law-sentinel-prod' `
        -Owner 'secops-lead@contoso.com' `
        -PublisherAppId '<publisher-app-id>' `
        -ClientId '<your-pnp-app-id>' -Tenant 'contoso.onmicrosoft.com' -WhatIf

    Shows what the bootstrap would do. Drop -WhatIf to run it.

.NOTES
    File:         Tools/Documenter/SharePoint/Initialize-SentinelDocsSite.ps1
    Repository:   Sentinel-As-Code
    Author:       noodlemctwoodle
    Website:      https://sentinel.blog
    Created:      2026-10-08
    Version:      0.1.0
    Last Updated: 2026-10-08
    Permissions:  SharePoint administrator; delegated Sites.FullControl.All on the sign-in app
    Requires:     PowerShell 7.4+, PnP.PowerShell 3.4.1

.LINK
    https://learn.microsoft.com/sharepoint/dev/solution-guidance/security-apponly-azuread

.LINK
    https://learn.microsoft.com/sharepoint/dev/general-development/site-collection-app-catalog
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory = $true)]
    [string]$SiteUrl,

    [Parameter(Mandatory = $false)]
    [string]$Title = 'iSOC Blueprint',

    [Parameter(Mandatory = $true)]
    [string]$Owner,

    [Parameter(Mandatory = $true)]
    [string]$PublisherAppId,

    [Parameter(Mandatory = $false)]
    [string]$PublisherAppName = 'Sentinel Documenter SharePoint publisher',

    [Parameter(Mandatory = $true)]
    [string]$ClientId,

    [Parameter(Mandatory = $true)]
    [string]$Tenant,

    [Parameter(Mandatory = $false)]
    [string]$TenantAdminUrl,

    [Parameter(Mandatory = $false)]
    [string]$AppPackagePath
)

$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'Private/SacSharePoint.ps1')

$SiteUrl = $SiteUrl.TrimEnd('/')
if (-not $TenantAdminUrl) {
    if ($SiteUrl -notmatch '^https://(?<t>[^./]+)\.sharepoint\.com/') { throw "Cannot derive the admin URL from '$SiteUrl'; pass -TenantAdminUrl." }
    $TenantAdminUrl = "https://$($Matches['t'])-admin.sharepoint.com"
}
if ($AppPackagePath -and -not (Test-Path -LiteralPath $AppPackagePath)) { throw "App package not found: $AppPackagePath" }

Write-Host 'iSOC Blueprint site bootstrap' -ForegroundColor Cyan
Write-Host "  Site      : $SiteUrl"
Write-Host "  Admin     : $TenantAdminUrl"
Write-Host "  Publisher : $PublisherAppName ($PublisherAppId)"

Connect-PnPOnline -Url $TenantAdminUrl -ClientId $ClientId -Tenant $Tenant -Interactive

# 1. Site --------------------------------------------------------------------
$existing = Get-PnPTenantSite -Identity $SiteUrl -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host '  Site exists.'
}
elseif ($PSCmdlet.ShouldProcess($SiteUrl, 'Create communication site')) {
    New-PnPSite -Type CommunicationSite -Title $Title -Url $SiteUrl -Owner $Owner -SiteDesign Blank -Wait | Out-Null
    Write-Host '  Site created.'
}

# 2. App catalogs ------------------------------------------------------------
$tenantCatalog = Get-PnPTenantAppCatalogUrl
if (-not $tenantCatalog) {
    throw 'This tenant has no app catalog. Create one first (Register-PnPAppCatalogSite, or the SharePoint admin centre), then re-run.'
}
$siteCatalog = Get-PnPSiteCollectionAppCatalog -ErrorAction SilentlyContinue |
    Where-Object { ([string]$_.AbsoluteUrl).TrimEnd('/') -eq $SiteUrl }
if ($siteCatalog) {
    Write-Host '  Site collection app catalog exists.'
}
elseif ($PSCmdlet.ShouldProcess($SiteUrl, 'Add site collection app catalog')) {
    Add-PnPSiteCollectionAppCatalog -Site $SiteUrl
    Write-Host '  Site collection app catalog added.'
}

# 3. Publisher access (Sites.Selected, this site only) -----------------------
$grant = Get-PnPEntraIDAppSitePermission -Site $SiteUrl -ErrorAction SilentlyContinue |
    Where-Object { @($_.Apps | ForEach-Object { [string]$_.Id }) -contains $PublisherAppId } |
    Select-Object -First 1
if ($grant -and (@($grant.Roles) -contains 'fullcontrol')) {
    Write-Host '  Publisher already has FullControl on the site.'
}
elseif ($grant) {
    if ($PSCmdlet.ShouldProcess($SiteUrl, "Raise $PublisherAppName to FullControl")) {
        Set-PnPEntraIDAppSitePermission -Site $SiteUrl -PermissionId $grant.Id -Permissions FullControl | Out-Null
        Write-Host '  Publisher raised to FullControl.'
    }
}
elseif ($PSCmdlet.ShouldProcess($SiteUrl, "Grant $PublisherAppName FullControl")) {
    Grant-PnPEntraIDAppSitePermission -AppId $PublisherAppId -DisplayName $PublisherAppName -Site $SiteUrl -Permissions FullControl | Out-Null
    Write-Host '  Publisher granted FullControl.'
}

# 4. Site settings -----------------------------------------------------------
if ($PSCmdlet.ShouldProcess($SiteUrl, 'Disable page comments and enable the mega menu')) {
    Connect-PnPOnline -Url $SiteUrl -ClientId $ClientId -Tenant $Tenant -Interactive
    Set-PnPSite -CommentsOnSitePagesDisabled:$true
    Set-PnPWeb -MegaMenuEnabled:$true
    Write-Host '  Page comments off, mega menu on.'
}

# 5. Optional first app deploy ------------------------------------------------
if ($AppPackagePath) {
    if (-not $WhatIfPreference) { Connect-PnPOnline -Url $SiteUrl -ClientId $ClientId -Tenant $Tenant -Interactive }
    Publish-SacAppPackage -Path $AppPackagePath | Out-Null
}

Write-Host "`nNext steps:" -ForegroundColor Green
Write-Host '  - Add the people who should read the site to its Visitors group, and no one else.'
Write-Host "  - Set the pipeline's site URL to $SiteUrl (see Docs/Pipelines/SharePoint-Publish.md)."
Write-Host '  - Run the SharePoint publish pipeline, or Publish-SentinelDocsSite.ps1 -Interactive -WhatIf to preview.'
