name: Deploy Sentinel-As-Code

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  EnableSentinelContentHub:
    name: Enable Sentinel Solutions and Configure Alert Rules
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to Azure (Attempt 1)
        continue-on-error: true
        id: login1
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SENTINEL_CLIENTID }}
          tenant-id: ${{ secrets.SENTINEL_TENANTID}}
          subscription-id: ${{ secrets.SENTINEL_SUBSCRIPTIONID }}
          environment: 'AzureCloud'
          audience: api://AzureADTokenExchange
          enable-AzPSSession: true
          
      - name: Enable Sentinel Solutions and Alert Rules
        uses: azure/powershell@v1
        continue-on-error: true
        with:
          inlineScript: |
            & "${{ github.workspace }}/Scripts/Set-SentinelContent.ps1" `
              -ResourceGroup '${{ vars.RESOURCE_GROUP }}' `
              -Workspace '${{ vars.WORKSPACENAME }}' `
              -Region '${{ vars.REGION }}' `
              -Solutions ${{ vars.SENTINELSOLUTIONS }} `
              -SeveritiesToInclude ${{ vars.ARSEVERITIES }} `
              -IsGov 'false'
          azPSVersion: 'latest'